import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MDNC TURISMO",
  description: "Generated by create marrumar",
  metadataBase: new URL("https://turismo.nuevacajamarca.gob.pe"),
  icons: {
    icon: '/logo.ico', 
  },
  openGraph: {
    title: 'Turismo NCM',
    description: 'Aventura, naturaleza y cultura en un solo lugar.',
    images: '/assets/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
