export const destinations = [
  {
    id: 'palestina',
    title: 'Cueva',
    subtitle: 'Palestina',
    description: 'Descubre la Cueva de Palestina, un misterioso mundo subterráneo.',
    image: '/assets/destinos/destino-1.webp',
    rating: 5,
  },
  {
    id: 'casacoto',
    title: 'Cascada',
    subtitle: 'Casacoto',
    description: 'Una cascada increíble rodeada de selva y paz.',
    image: '/assets/destinos/destino-2.webp',
    rating: 4,
  },
  {
    id: 'mirador',
    title: 'Cerro',
    subtitle: 'Mirador',
    description: 'Vistas espectaculares desde el punto más alto.',
    image: '/assets/destinos/destino-3.webp',
    rating: 4,
  },
  {
    id: 'tunel',
    title: 'Túnel',
    subtitle: 'San Juan',
    description: 'Atrévete a recorrer este túnel natural lleno de historia y misterio.',
    image: '/assets/destinos/destino-4.webp',
    rating: 4,
  },
  {
    id: 'cascadaselva',
    title: 'Cascada',
    subtitle: 'Selva Escondida',
    description: 'Un rincón oculto en la selva con una caída de agua cristalina.',
    image: '/assets/destinos/destino-5.webp',
    rating: 5,
  },
  {
    id: 'piedras',
    title: 'Formación Rocosa',
    subtitle: 'Las Piedras',
    description: 'Formaciones rocosas milenarias que despiertan la imaginación.',
    image: '/assets/destinos/destino-6.webp',
    rating: 3,
  },
];
